### ISSUE TITLE
支持 https://example.com/push/keyxxxxxxxx/ 格式

### ISSUE THREAD

**Issue by harv** [xlvecle/Bark-Chrome-Extension#1]
https://github.com/xlvecle/Bark-Chrome-Extension/blob/b5e32128bd4ec887ee26e1e6cd5e74827a5b4b53/src/options.js#L18

`new URL(server_url).origin` 只能取到 https://example.com ，正确的应该是 https://example.com/push

建议改成 `server_url.substr(0, server_url.lastIndexOf("/", server_url.lastIndexOf("/") - 1))`

**Comment by xlvecle** [comment]
不错的建议👍，之前只考虑了Bark的server是 https://example.com/ping，没有考虑到用户会放在二级路由下面 。
