### ISSUE TITLE
Can't work

### ISSUE THREAD

**Issue by zjy369** [xlvecle/Bark-Chrome-Extension#10]
if (full_server_url.startsWith("http")) 

full_server_url="selection#https********"

ios

**Comment by xlvecle** [comment]
会很快修复这个问题，不过需要等chrome商店审核

**Comment by xlvecle** [comment]
没有理解具体的问题，可以描述的更清晰一点吗

**Comment by zjy369** [comment]
> 没有理解具体的问题，可以描述的更清晰一点吗

鼠标右键选中文本，选择推送ios设备，上面那段代码会默认走到安卓

**Comment by xlvecle** [comment]
好的，这个会快修复，需要等一下Chrome商店审核。

**Comment by xlvecle** [comment]
已经提交审核，带来的不便非常抱歉~

**Comment by zjy369** [comment]
> 已经提交审核，带来的不便非常抱歉〜

nice
