### ISSUE TITLE
请问有没有把Bark的Chrome插件发布到Edge商店的想法

### ISSUE THREAD

**Issue by luojianxhlxt** [xlvecle/Bark-Chrome-Extension#15]
最近Edge浏览器挺好用的，请问有没有把Bark的Chrome插件发布到Edge商店的想法。
虽然Edge可以加载谷歌商店的插件，但是能发布到微软也不错哈。
只是个建议，打扰咯。

**Comment by xlvecle** [comment]
可以，我也很喜欢edge，我最近研究下，之前有点忙

**Comment by Stonestonestone** [comment]
请问可以发布到firefox商店吗?一直以来习惯了firefox也很喜欢您这个应用

----

呃,自己提交可以用了,感谢作者
