### ISSUE TITLE
src.crx文件无法安装

### ISSUE THREAD

**Issue by lifengsbotlp** [xlvecle/Bark-Chrome-Extension#2]
Chrome浏览器版本 67.0.3396.99（正式版本） （64 位）；
error：无法从网站添加应用、扩展程序和用户脚本

**Comment by xlvecle** [comment]
chrome新版本禁止了直接安装crx，请将源代码直接再插件开发界面加载进来。
如果懒得设置，稍后会上架到chrome应用商店。

**Comment by TrayBer** [comment]
已经上架了谷歌应用商店了吗？

**Comment by xlvecle** [comment]
> 已经上架了谷歌应用商店了吗？

因为信用卡问题折腾了很久，最近总算要搞定了

**Comment by xlvecle** [comment]
![image](https://user-images.githubusercontent.com/8241747/50208634-a2142c00-03ac-11e9-8dcf-3d37689e31d0.png)

**Comment by xlvecle** [comment]
> 已经上架了谷歌应用商店了吗？

https://chrome.google.com/webstore/detail/bark/pmlkbdbpglkgbgopghdcmohdcmladeii

**Comment by TrayBer** [comment]
感谢，感谢！
