### ISSUE TITLE
希望添加自动复制推送内容的参数

### ISSUE THREAD

**Issue by Finb** [xlvecle/Bark-Chrome-Extension#4]
hI~
平常经常使用这个扩展，大部分情况都是将内容推送到手机，然后下拉复制。
现在我给Bark加上了 收到推送时自动复制推送内容的功能，只需要在推送时携带参数 automaticallyCopy=1 即可
是否可以给这个扩展加上这个参数呢？

**Comment by chenbaocn** [comment]
目前总共实现了哪些参数呢？

**Comment by Finb** [comment]
@chenbaocn 
APP内有示例
url  点击推送会跳转到这个url
copy 复制推送时，将只复制copy的值
automaticallyCopy 收到推送时，自动将推送内容复制到粘贴板 （这个还没上架）

**Comment by Finb** [comment]
![](http://wx4.sinaimg.cn/mw690/0060lm7Tly1fyaqyhzdnxg30660dcu0h.gif)
效果大概是这样，提交了一个PR
不一定要合并喔，就是我个人的使用偏好

**Comment by xlvecle** [comment]
好啊好啊，我这两天会把插件发到chrome store，刚好一起做了

**Comment by xlvecle** [comment]
> ![](https://camo.githubusercontent.com/ec12b49372193b8ae7b1f536f857db045c029627/687474703a2f2f7778342e73696e61696d672e636e2f6d773639302f303036306c6d37546c79316679617179687a646e7867333036363064637530682e676966)
> 效果大概是这样，提交了一个PR
> 不一定要合并喔，就是我个人的使用偏好

我发到chrome AppStore了- -这个feature没有打包过去，因为自己在用的时候发现偶尔有一些不需要自动复制的场景- -有时间搞得话可以考虑提供选项

**Comment by 8183736** [comment]
> > ![](https://camo.githubusercontent.com/ec12b49372193b8ae7b1f536f857db045c029627/687474703a2f2f7778342e73696e61696d672e636e2f6d773639302f303036306c6d37546c79316679617179687a646e7867333036363064637530682e676966)
> > 效果大概是这样，提交了一个PR
> > 不一定要合并喔，就是我个人的使用偏好
> 
> 我发到chrome AppStore了- -这个feature没有打包过去，因为自己在用的时候发现偶尔有一些不需要自动复制的场景- -有时间搞得话可以考虑提供选项

希望开启这个功能哦，如果不需要，自行在device push URL中删除autocopy参数就好啦😂
