### ISSUE TITLE
浏览器选中文本后，右键没有Bark选项

### ISSUE THREAD

**Issue by luojianxhlxt** [xlvecle/Bark-Chrome-Extension#8]
浏览器刚打开的时候，页面上选中了文本后，右键没有Bark的选项
需要进入Bark浏览器扩展的设置页面一次，右键的Bark才会出现
浏览器版本Cent Browser版本 4.0.9.112（正式版本） （64 位） (Chromium 74.0.3729.169)
扩展版本1.2.0

**Comment by xlvecle** [comment]
fixed at  #9

**Comment by xlvecle** [comment]
商店版本等Google随缘审核吧，一般四五个工作日:D

**Comment by xlvecle** [comment]
审核通过了
